style: com.yersmagit.lessonsdisplayer format (#86)
https://github.com/Class-Widgets/plugin-plaza/actions/runs/22580805222/job/65412079974#annotation:7:227

使用 pre-commit 规范格式

```shell
Run j178/prek-action@v1
Run # Resolve prek version
Run # Installing prek
Installing prek v0.3.4
Run actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7
Cache hit for: prek-v1|Linux|X64|/opt/hostedtoolcache/Python/3.11.14/x64|179f76d2d39534693a7644e5068138e0db742d8d182595c56aa85fe02e9a783b
Received 24670501 of 24670501 (100.0%), 38.0 MBs/sec
Cache Size: ~24 MB (24670501 B)
/usr/bin/tar -xf /home/runner/work/_temp/3eaf93a3-d987-48ee-8dfd-92e0f26c0840/cache.tzst -P -C /home/runner/work/plugin-plaza/plugin-plaza --use-compress-program unzstd
Cache restored successfully
Cache restored from key: prek-v1|Linux|X64|/opt/hostedtoolcache/Python/3.11.14/x64|179f76d2d39534693a7644e5068138e0db742d8d182595c56aa85fe02e9a783b
Run # Running prek
check json...............................................................Passed
check yaml...............................................................Passed
trim trailing whitespace.................................................Passed
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

  Fixing ClassWidgets2/plugins/manifest/com.yersmagit.lessonsdisplayer.json
  Fixing Plugins/plugin_list.json
mixed line ending........................................................Failed
- hook id: mixed-line-ending
- exit code: 1
- files were modified by this hook

  Fixing ClassWidgets2/plugins/manifest/com.yersmagit.lessonsdisplayer.json
prettier.................................................................Failed
- hook id: prettier
- files were modified by this hook

  .github/ISSUE_TEMPLATE/plugin-add.yml 69ms (unchanged)
  Banner/banner.json 40ms (unchanged)
  ClassWidgets2/plugins/manifest/com.yersmagit.lessonsdisplayer.json 9ms (unchanged)
  .github/workflows/cw2_plugin_submission_review.yml 121ms (unchanged)
  README.md 54ms (unchanged)
  ClassWidgets2/tags.json 5ms (unchanged)
  .github/workflows/validate_cw2_plugin_list.yml 57ms (unchanged)
  .github/workflows/plugin_submission_review.yml 130ms (unchanged)
  .github/workflows/update_plugins.yml 26ms (unchanged)
  ClassWidgets2/plugins/manifest/com.laoshui.yiyan.json 32ms (unchanged)
  Plugins/tags.json 3ms (unchanged)
  .github/ISSUE_TEMPLATE/cw2-plugin-add.yml 12ms (unchanged)
  .github/workflows/validate_plugin_list.yml 57ms (unchanged)
  ClassWidgets2/plugins/manifest/com.laoshui.voicehub.json 46ms (unchanged)
  ClassWidgets2/plugins/index.json 26ms (unchanged)
  Plugins/plugin_list.json 76ms
  Plugins/plaza_detail.json 5ms (unchanged)
  ClassWidgets2/plugins/manifest/com.rinlit.test.json 4ms (unchanged)
  ClassWidgets2/banners/home.json 51ms (unchanged)
  .github/workflows/update_cw2_plugins.yml 58ms (unchanged)
  ClassWidgets2/plugins/manifest/com.rinlit.countdowndays.json 12ms (unchanged)
  .pre-commit-config.yaml 17ms (unchanged)
  ClassWidgets2/plugins/manifest/com.hpdnya.tts.json 8ms (unchanged)

hint: Some hooks made changes to the files.
If you are seeing this message in CI, reproduce locally with: `prek run --all-files`
To run prek as part of git workflow, use `prek install` to set up git hooks.

All changes made by hooks:
diff --git a/ClassWidgets2/plugins/manifest/com.yersmagit.lessonsdisplayer.json b/ClassWidgets2/plugins/manifest/com.yersmagit.lessonsdisplayer.json
index 5904085..5c75cf8 100644
--- a/ClassWidgets2/plugins/manifest/com.yersmagit.lessonsdisplayer.json
+++ b/ClassWidgets2/plugins/manifest/com.yersmagit.lessonsdisplayer.json
@@ -1,14 +1,13 @@
-{
-  "id": "com.yersmagit.lessonsdisplayer",
-  "name": "Lessons Displayer 全量展示课程",
-  "version": "0.1.7",
-  "api_version": ">=0.2.0",
-  "entry": "main.py",
-  "author": "Yersmagit",
-  "description": "看看今天有什么课？LessonsDisplayer 正在迁移到 CW2 ！",
-  "url": "https://github.com/Yersmagit/cw2-lessons-displayer",
-  "readme": "README.md",
-  "icon": "icon.png",
-  "tags": ["tools", "classroom_environment", "information", "subject"]
-}
-
+{
+  "id": "com.yersmagit.lessonsdisplayer",
+  "name": "Lessons Displayer 全量展示课程",
+  "version": "0.1.7",
+  "api_version": ">=0.2.0",
+  "entry": "main.py",
+  "author": "Yersmagit",
+  "description": "看看今天有什么课？LessonsDisplayer 正在迁移到 CW2 ！",
+  "url": "https://github.com/Yersmagit/cw2-lessons-displayer",
+  "readme": "README.md",
+  "icon": "icon.png",
+  "tags": ["tools", "classroom_environment", "information", "subject"]
+}
Error: Process completed with exit code 1.
```